name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '* $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '\<*_&#@`'
template: |
  ## Changelog
  $CHANGES

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'documentation'
      - 'style'
      - 'refactor'
      - 'performance'
      - 'test'
      - 'chore'
      - 'ci'
      - 'revert'
  default: patch

exclude-labels:
  - 'skip-changelog'

categories:
  - title: 'Features'
    labels: 
      - 'feature'
  - title: 'Fixes'
    labels: 
      - 'bug'
  - title: 'Documentation'
    labels: 
      - 'documentation'
  - title: 'Other'
    labels:
      - 'style'
      - 'refactor'
      - 'performance'
      - 'test'
      - 'chore'
      - 'ci'
      - 'revert'

autolabeler:
  - label: 'feature'
    title:
      - '/^feat/'
  - label: 'bug'
    title:
      - '/^fix/'
  - label: 'documentation'
    title:
      - '/^docs/'
  - label: 'style'
    title:
      - '/^style/'
  - label: 'refactor'
    title:
      - '/^refactor/'
  - label: 'performance'
    title:
      - '/^perf/'
  - label: 'test'
    title:
      - '/^test/'
  - label: 'chore'
    title:
      - '/^chore/'
  - label: 'ci'
    title:
      - '/^ci/'
  - label: 'revert'
    title:
      - '/^revert/'
