version: "2"

linters:
  default: none
  disable:
    # - exhaustivestruct
    - depguard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - asciicheck
    - goconst
    # - revive

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  settings:
    golines:
      max-len: 88
      tab-len: 2

