version: 2
project_name: spoofdpi

before:
  hooks:
    - go mod tidy

builds:
  - id: 'freebsd'
    goos: [freebsd]
    goarch: [ "{{ .Env.TARGET_ARCH }}" ] 
    env: [ "CGO_ENABLED=1" ]
    ldflags:
      - -s -w
      - -X "main.Version={{.Version}}"
      - -X "main.Commit={{.ShortCommit}}"
    main: ./cmd/spoofdpi
    binary: '{{ .ProjectName }}'

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    builds: [ "freebsd" ]
