version: 2
project_name: spoofdpi

before:
  hooks:
    - go mod tidy
    - sh -c 'git rev-parse --short HEAD > COMMIT'

builds:
  # ---------------------------------------------------------------------------
  # Linux Builds (Pure Go / Static)
  # ---------------------------------------------------------------------------
  # Can be built on any OS (macOS/Linux) since CGO is disabled.
  - id: 'linux'
    goos: [linux]
    goarch: 
      - '386'
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      - riscv64
    gomips: [softfloat]
    env: [ "CGO_ENABLED=0" ]
    ldflags:
      - -s -w
      - -X "main.version={{ .Version }}"
      - -X "main.commit={{ .ShortCommit }}"
      - -X "main.build=goreleaser"
    main: ./cmd/spoofdpi
    binary: '{{ .ProjectName }}'

  # ---------------------------------------------------------------------------
  # macOS Builds (CGO Enabled)
  # ---------------------------------------------------------------------------
  # Requires a macOS runner.
  - id: 'darwin'
    goos: [darwin]
    goarch: [amd64, arm64]
    env: [ "CGO_ENABLED=1" ]
    ldflags:
      - -s -w
      - -X "main.version={{ .Version }}"
      - -X "main.commit={{ .ShortCommit }}"
      - -X "main.build=goreleaser"
    main: ./cmd/spoofdpi
    binary: '{{ .ProjectName }}'

source:
  enabled: true
  prefix_template: '{{ .ProjectName }}-{{ .Version }}/'
  files:
  - COMMIT

archives:
  - id: default
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "mips64" }}mips64_hardfloat
      {{- else if eq .Arch "mips64le" }}mips64le_hardfloat
      {{- else }}{{ .Arch }}{{ end -}}
    formats: ['tar.gz']
    # Explicitly list builds to include (optional but good for clarity)
    ids: ['linux', 'darwin']
      

# Linux Packages
nfpms:
  - id: packages
    ids: ['linux'] 
    file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    vendor: xvzc
    homepage: https://github.com/xvzc/SpoofDPI
    maintainer: xvzc
    description: A simple and fast anti-censorship tool written in Go
    license: Apache-2.0
    bindir: /usr/local/bin
    section: networking
    priority: optional

# Generate Software Bill of Materials
sboms:
  - artifacts: archive

checksum:
  name_template: 'checksums.txt'

signs:
- cmd: cosign
  signature: "${artifact}.sigstore.json"
  artifacts: checksum
  args:
    - sign-blob
    - "--bundle=${signature}"
    - "${artifact}"
    - --yes
