version: 2
project_name: spoofdpi

before:
  hooks:
    - go mod tidy

builds:
  - id: 'linux-pure'
    goos: [linux]
    goarch: [amd64, arm64, mips, mipsle]
    gomips: [softfloat]
    env: [ "CGO_ENABLED=0" ]
    ldflags:
      - -s -w
      - -X "main.version={{.Version}}"
      - -X "main.commit={{.ShortCommit}}"
    main: ./cmd/spoofdpi
    binary: '{{ .ProjectName }}'

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    builds: [ "linux-pure" ]
