version: 2
project_name: spoofdpi

before:
  hooks:
    - go mod tidy

builds:
  - id: 'darwin-amd64'
    goos: [darwin]
    goarch: [amd64]
    env: [ "CGO_ENABLED=1", "CC=clang -arch x86_64", "CXX=clang++ -arch x86_64" ]
    ldflags:
      - -s -w
      - -X "main.version={{.Version}}"
      - -X "main.commit={{.ShortCommit}}"
    main: ./cmd/spoofdpi
    binary: '{{ .ProjectName }}'

  - id: 'darwin-arm64'
    goos: [darwin]
    goarch: [arm64]
    env: [ "CGO_ENABLED=1", "CC=clang -arch arm64", "CXX=clang++ -arch arm64" ]
    ldflags:
      - -s -w
      - -X "main.version={{.Version}}"
      - -X "main.commit={{.ShortCommit}}"
    main: ./cmd/spoofdpi
    binary: '{{ .ProjectName }}'

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    builds: [ "darwin-amd64", "darwin-arm64" ]
