name: Lint PR

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

jobs:
  commitlint:
    name: commitlint
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install commitlint
        run: npm install --no-save --ignore-scripts @commitlint/cli @commitlint/config-conventional

      - name: Lint PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo "$PR_TITLE" | npx commitlint --verbose

      - name: Lint commits in PR
        run: |
          npx commitlint \
            --from ${{ github.event.pull_request.base.sha }} \
            --to ${{ github.event.pull_request.head.sha }} \
            --verbose
